name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.10
  - pip=24.0
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4 -c pytorch -c nvidia
  - pip:
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.4.0+cu118
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.19.0+cu118
    - timm
    - diffusers
    - accelerate
    - triton==3.0.0
